sudo: false
language: objective-c
osx_image: xcode7.1

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool -project Swiftline.xcodeproj -scheme Swiftline  build test -sdk macosx GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash)
